on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
name: linter

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.x

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.50.1
